# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ForeignKey(help_text='The profile photo for this user.', blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE, to='photos.Photo'),
        ),
    ]
